version: "3.9"
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=1q23456
    volumes:
      - './data/mongo:/data/db'

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
    volumes:
      - './data/mysql:/var/lib/mysql'

  redis:
    container_name: redis
    image: redis

    # Apply custom arguments to redis startup
    command: ["redis-server", "--appendonly", "yes"]
    #command: ["redis-server", "--appendonly", "yes", "--requirepass ${REDIS_PASSWORD}"]
    volumes:
      - ./data/redis:/data

    ports:
      - "6379:6379"

    restart: always

#  arangodb_db_container:
#    image: arangodb:latest
#    environment:
#      ARANGO_ROOT_PASSWORD: 1234567
#    ports:
#      - 8529:8529
#    volumes:
#      - ./data/arangodb3:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8088:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  neo4j:
    container_name: neo4j
    image: neo4j
    environment:
      #NEO4J_AUTH: neo4j:12345678
      NEO4J_AUTH: none
    volumes:
      - ./data/neo4j:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
